name: Set App Secrets

on: [push]

jobs:
  set-secrets:
    runs-on: windows-latest

    steps:
    - name: Set environment variables
      env:
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      run: echo "Secrets have been set for the app."
