name: Set App Secrets

on: [push]

jobs:
  set-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      run: echo "Secrets have been set for the app."